include ../../Makefile.param

#库文件名
TARGET := libplayback.a
#库文类型,SO:动态库,A:静态库,BIN:可执行文件
#TRAGET_TYPE := SO
TARGET_TYPE := A
#TARGET_TYPE := BIN

#动态库(仅编码可执行文件需要)
SLIBS := 
#静态库(仅编码可执行文件需要)
DLIBS :=

include ../../Makefile.temp